### ISSUE TITLE
mcmicro_io.zip cell and nucleus bitmasks are the same

### ISSUE THREAD

**Issue by keller-mark** [scverse/spatialdata-notebooks#52]
Is this expected?

![Screenshot 2023-09-20 at 10 52 38 AM](https://github.com/scverse/spatialdata-notebooks/assets/7525285/16821f73-14eb-42c3-b792-e54ce2d96ce4)
![Screenshot 2023-09-20 at 10 52 50 AM](https://github.com/scverse/spatialdata-notebooks/assets/7525285/e5dd8a49-2eaa-44ea-8989-3950330b8f57)
![Screenshot 2023-09-20 at 10 52 56 AM](https://github.com/scverse/spatialdata-notebooks/assets/7525285/ff9d3fa8-0f63-454a-a4db-4993a17c16f7)

**Comment by keller-mark** [comment]
It also could be improved by having more meaningful labels in channels_metadata - it seems like there are good names in table.var.index
```
"channels_metadata": {
        "channels": [
            {
                "label": 0
            },
            {
                "label": 1
            },
            {
                "label": 2
            },
            {
                "label": 3
            },
            {
                "label": 4
            },
            {
                "label": 5
            },
            {
                "label": 6
            },
            {
                "label": 7
            },
            {
                "label": 8
            },
            {
                "label": 9
            },
            {
                "label": 10
            },
            {
                "label": 11
            }
        ]
    },
```

**Comment by LucaMarconato** [comment]
@keller-mark could you please try using this PR, which improved the `mcmicro` reader: https://github.com/scverse/spatialdata-io/pull/28?

**Comment by LucaMarconato** [comment]
Actually, this doesn't fix the problem, I will check for a solution.

**Comment by LucaMarconato** [comment]
Getting back to this. The incoming PR (I'll try to merge it today) https://github.com/scverse/spatialdata-io/pull/28 assigns the channel names to the image (and generalizes the reader to support more complex outputs of the mcmicro pipeline).

Regarding the cell vs nuclei, I examined the code and the files, and realized that problem is already present in the data, and therefore is not due to our reader. I reported this in the mcmicro repository https://github.com/labsyspharm/mcmicro/issues/531.
