### ISSUE TITLE
NotImplementedError: Multiscale images are not implemented yet

### ISSUE THREAD

**Issue by duongvtt96** [scverse/spatialdata-notebooks#70]
Hi, I tried to run the [densenet.ipynb notebook](https://spatialdata.scverse.org/en/latest/tutorials/notebooks/notebooks/examples/densenet.html), but faced an error when creating `ImageTilesDataset`: NotImplementedError: Multiscale images are not implemented yet.
The original code is 
`dataset = ImageTilesDataset(
    sdata=merged,
    regions_to_images={"cell_circles": "CytAssist_FFPE_Human_Breast_Cancer_full_image"},
    tile_dim_in_units=3 * xenium_circles_diameter,
    tile_dim_in_pixels=32,
    target_coordinate_system="aligned",
    transform=my_transform,
)`
and was modified to:
`dataset = ImageTilesDataset(
    sdata=merged,
    regions_to_images={"cell_circles": "CytAssist_FFPE_Human_Breast_Cancer_full_image"},
    tile_dim_in_units=3 * xenium_circles_diameter,
    #tile_dim_in_pixels=32,
    #target_coordinate_system="aligned",
    regions_to_coordinate_systems={"cell_circles": "aligned"},
    transform=my_transform,
)`
with spatialdata version=0.0.16.dev24+ga5336d8 installed from GitHub. 

Do you have any suggestions for this issue? Thank you.

**Comment by LucaMarconato** [comment]
Thanks for reporting, we tested the notebook before making a release so it should work on the latest version of spatialdata and we are aware that it currently doesn't work on the main branch. In fact we improved the `ImageTilesDataset` class with this PR https://github.com/scverse/spatialdata/pull/299 but we haven't updated the notebook yet.

I will do this before the next release, but also I will keep you updated here as soon as it is ready, so that you don't have to wait for the next release.

**Comment by LucaMarconato** [comment]
@duongvtt96, with https://github.com/scverse/spatialdata/pull/439 merged, the new `ImageTilesDataset` class now work also for multiscale images and multiscale labels. I will update the example notebook for the 0.1.0 release but you can already use the code if you install `spatialdata` from the `main` branch.
